export const REJECTION_REASON = {
  PAN_VERIFICATION_FAILED: 'PAN_VERIFICATION_FAILED',
  MIN_AGE_BRE_FAILED: 'MIN_AGE_BRE_FAILED',
  MAX_AGE_BRE_FAILED: 'MAX_AGE_BRE_FAILED',
  NEGATIVE_PINCODE: 'NEGATIVE_PINCODE',
  NEGATIVE_CITY: 'NEGATIVE_CITY',
  NEGATIVE_STATE: 'NEGATIVE_STATE',
  GENDER_BRE_FAILED: 'GENDER_BRE_FAILED',
  OCCUPATION_FAILED: 'OCCUPATION_FAILED',
  REJECTED_BY_CLIENTS: 'REJECTED_BY_CLIENTS',
  NEW_TO_CREDIT: 'NEW_TO_CREDIT',
  CIBIL_SCORE_LOW: 'CIBIL_SCORE_LOW',
  BUREAU_ADVERSE_TRADELINE: 'BUREAU_ADVERSE_TRADELINE',
  BUREAU_ENQUIRIES_EXCEEDED: 'BUREAU_ENQUIRIES_EXCEEDED',
  BUREAU_DPD_FAILED: 'BUREAU_DPD_FAILED',
  BUREAU_RESTRUCTURED_LOAN: 'BUREAU_RESTRUCTURED_LOAN',
  BUREAU_SMA_PWOS_TRADELINE: 'BUREAU_SMA_PWOS_TRADELINE',
  BUREAU_ACTIVE_MFI_LOAN: 'BUREAU_ACTIVE_MFI_LOAN',
  KYC_AADHAAR_MISMATCH: 'KYC_AADHAAR_MISMATCH',
  BUREAU_IDENTITY_MISMATCH: 'BUREAU_IDENTITY_MISMATCH',
} as const;

export type RejectionReason = (typeof REJECTION_REASON)[keyof typeof REJECTION_REASON];