export const REJECTION_REASON = {
  PAN_VERIFICATION_FAILED: 'PAN_VERIFICATION_FAILED',
  MIN_AGE_BRE_FAILED: 'MIN_AGE_BRE_FAILED',
  MAX_AGE_BRE_FAILED: 'MAX_AGE_BRE_FAILED',
  NEGATIVE_PINCODE: 'NEGATIVE_PINCODE',
  NEGATIVE_CITY: 'NEGATIVE_CITY',
  NEGATIVE_STATE: 'NEGATIVE_STATE',
  OCCUPATION_FAILED: 'OCCUPATION_FAILED',
} as const;

export type RejectionReason = (typeof REJECTION_REASON)[keyof typeof REJECTION_REASON];
