export const INDIAN_STATES = [
    { name: 'ANDHRA PRADESH',        code: 'AP' },
    { name: 'ARUNACHAL PRADESH',     code: 'AR' },
    { name: 'ASSAM',                 code: 'AS' },
    { name: 'BIHAR',                 code: 'BR' },
    { name: 'CHHATTISGARH',         code: 'CG' },
    { name: 'GOA',                   code: 'GA' },
    { name: 'GUJARAT',               code: 'GJ' },
    { name: 'HARYANA',               code: 'HR' },
    { name: 'HIMACHAL PRADESH',      code: 'HP' },
    { name: 'JHARKHAND',             code: 'JH' },
    { name: 'KARNATAKA',             code: 'KA' },
    { name: 'KERALA',                code: 'KL' },
    { name: 'MADHYA PRADESH',        code: 'MP' },
    { name: 'MAHARASHTRA',           code: 'MH' },
    { name: 'MANIPUR',               code: 'MN' },
    { name: 'MEGHALAYA',             code: 'ML' },
    { name: 'MIZORAM',               code: 'MZ' },
    { name: 'NAGALAND',              code: 'NL' },
    { name: 'ODISHA',                code: 'OD' },
    { name: 'PUNJAB',                code: 'PB' },
    { name: 'RAJASTHAN',             code: 'RJ' },
    { name: 'SIKKIM',                code: 'SK' },
    { name: 'TAMIL NADU',            code: 'TN' },
    { name: 'TELANGANA',             code: 'TS' },
    { name: 'TRIPURA',               code: 'TR' },
    { name: 'UTTAR PRADESH',         code: 'UP' },
    { name: 'UTTARAKHAND',           code: 'UK' },
    { name: 'WEST BENGAL',           code: 'WB' },
    { name: 'ANDAMAN AND NICOBAR',   code: 'AN' },
    { name: 'CHANDIGARH',            code: 'CH' },
    { name: 'DADRA AND NAGAR HAVELI',code: 'DH' },
    { name: 'DAMAN AND DIU',         code: 'DD' },
    { name: 'DELHI',                 code: 'DL' },
    { name: 'JAMMU AND KASHMIR',     code: 'JK' },
    { name: 'LADAKH',                code: 'LA' },
    { name: 'LAKSHADWEEP',           code: 'LD' },
    { name: 'PUDUCHERRY',            code: 'PY' },
] as const;